djangoProject/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('detail<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views, api

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/checkout', views.OrderCreate.as_view(), name='create_order'),
    path('aplly/<int:order_id>/', views.OofCodeApply.as_view(), name="apply_code"),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('order/detail/<int:order_id>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/remove/<int:order_id>', views.OrderRemoveView.as_view(), name='order_remove'),
    path('orderitem/<int:pk>', api.OrderItemView.as_view(), name='order_item'),
]

home/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    parent = models.ForeignKey(to='self', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, verbose_name=_('is active'),
                                    help_text=_('to not showing this category disable this field'))
    is_root = models.BooleanField(default=False, verbose_name=_('is root category'),
                                  help_text=_('if this is root category mark this field'))


class OffCode(models.Model):
    is_active = models.BooleanField(default=True, verbose_name=_('is active'),
                                    help_text=_('to disable this off code disable this field'))
    type = models.CharField(max_length=10, choices=(('p', _('percent')),
                                                    ('a', _('amount'))), verbose_name=_('off code type'))
    amount = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.amount} {self.type}'


serve_type = (
    ('s', _('single')),
    ('o_t', _('one and two person')),
    ('s_b', _('big and small'))
)


class Food(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name=_('category'))
    name = models.CharField(max_lengt=255, verbose_name=_('name'))
    description = models.TextField(verbose_name=_('description'),
                                   help_text=_('write like example (meet 150g, chicken 250g)'))
    serve_type = models.CharField(choices=serve_type, verbose_name=_('serve type'))
    first_price = models.IntegerField(verbose_name=_('price one person'))
    second_price = models.IntegerField(verbose_name=_('price for two person'),
                                    help_text=_('if this food is for two serve type fill this field'), null=True,
                                    blank=True)
    off_code_for_first_price = models.ForeignKey(to=OffCode, on_delete=models.SET_NULL, null=True, blank=True)
    off_code_for_second_price = models.ForeignKey(to=OffCode, on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name=_('is active'),
                                    help_text=_('to not showing this food disable this field'))

    def price_return(self):
        if self.serve_type == 's':
            if self.off_code_for_first_price:
                ...

    def first_price_calculate(self):
        off_code = self.off_code_for_first_price
        if off_code:
            if off_code.type == 'p':
                return self.first_price * off_code.amount / 100
            return self.first_price - off_code.amount

    def second_price_calculate(self):
        off_code = self.off_code_for_second_price
        if off_code.type == 'p':
            return self.second_price * off_code.amount / 100
        return self.second_price - off_code.amount

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from product.models import Product, Category
from orders.forms import CartAddForm


# Create your views here.

class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(is_active=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'index.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, 'product.html', {'product': product, "form": form})

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small><br/>
    <p>{{ product.price }} Toman</p>
    <img src="{{ product.image.url }}" alt="{{ product.name }}">
    <p>{{ product.descriptions }}</p>
    <br>
    <br>
    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add to cart">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}

    {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
                    aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% for sub in category.sub_cat.all %}
                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <br>
    <br>
    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}