djangoProject/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('detail<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views, api

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/checkout', views.OrderCreate.as_view(), name='create_order'),
    path('aplly/<int:order_id>/', views.OofCodeApply.as_view(), name="apply_code"),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('order/detail/<int:order_id>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/remove/<int:order_id>', views.OrderRemoveView.as_view(), name='order_remove'),
    path('orderitem/<int:pk>', api.OrderItemView.as_view(), name='order_item'),
]

orders/models.py
from django.db import models
from core.models import BaseModel
# Create your models here.
from customer.models import User, Address
from product.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(BaseModel):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='orders')
    user_address = models.ForeignKey(to=Address, on_delete=models.CASCADE, default=None, null=True)
    paid = models.BooleanField(default=False)
    checkout = models.BooleanField(default=False)
    discount = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"{self.user} - {self.id}"

    def set_discount(self, value):
        self.discount = value

    @property
    def get_total_price(self):
        total = sum(item.get_cost for item in self.items.all())
        if self.discount:
            return total - total * int(self.discount) / 100
        return total


class OrderItem(BaseModel):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, related_name='order_item')
    price = models.IntegerField()
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return str(self.id)

    @property
    def get_cost(self):
        return self.quantity * self.price


class OofCode(BaseModel):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateField()
    valid_to = models.DateField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])

    def __str__(self):
        return self.code

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=20)


class OofCodeForm(forms.Form):
    code = forms.CharField()

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views import View
from .cart import Cart
from product.models import Product
from .forms import CartAddForm, OofCodeForm
from .models import Address
# Create your views here.
from .models import Order, OrderItem, OofCode


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        form = OofCodeForm()
        return render(request, 'cart.html', {'cart': cart, 'form': form})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        if product:
            cart.add(product, int(request.POST['quantity']))
        return HttpResponse({'redirect': redirect('home:home').url})


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderCreate(View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        items = order.items.all()
        form = OofCodeForm()
        return redirect('orders:order_detail', order_id=order.id)


class OofCodeApply(View):
    def post(self, request, order_id):
        order = Order.objects.get(id=order_id)
        form = OofCodeForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            code = OofCode.objects.get(code=code)
            order.set_discount(code.discount)
            order.save()
        return redirect('orders:order_detail', order_id=order_id)


class OrdersView(View):
    def get(self, request):
        orders = Order.objects.filter(user=request.user, is_deleted=False)
        return render(request, 'orders.html', {'orders': orders})


class OrderDetail(View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id, is_deleted=False, checkout=False, user=request.user)
        items = order.items.all()
        form = OofCodeForm()
        address = Address.objects.get(user=request.user)
        return render(request, 'checkout.html', {"order": order, 'form': form, 'items': items, 'address': address})


class OrderRemoveView(View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        order.is_deleted = True
        order.save()
        return redirect('orders:orders')

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-success">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td colspan="2">Larry the Bird</td>
            <td>@twitter</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-success table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit price</th>
            <th scope="col">Total price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="3"></td>
            <td>{{ order.get_total_price }}</td>
        </tr>

        </tbody>
    </table>
    <form action="{% url 'orders:apply_code' order.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="apply code">
    </form>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-success table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">Total price</th>
            <th scope="col">Remove</th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order.id }}</td>
                <td>{{ order.get_total_price }}</td>
                <td><a href="{% url 'orders:order_remove' order.id %}">remove</a></td>
                <td><a href="{% url 'orders:order_detail' order.id %}">detail</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}