customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('login_verify/', views.UserLoginVerifyView.as_view(), name='login_verify'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout')
]

djangoProject/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('detail<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views, api

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/checkout', views.OrderCreate.as_view(), name='create_order'),
    path('aplly/<int:order_id>/', views.OofCodeApply.as_view(), name="apply_code"),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('order/detail/<int:order_id>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/remove/<int:order_id>', views.OrderRemoveView.as_view(), name='order_remove'),
    path('orderitem/<int:pk>', api.OrderItemView.as_view(), name='order_item'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'customer:user_logout' %}">Logout</a>
                <a class="nav-link active" href="{% url 'orders:orders' %}">Orders</a>
            {% else %}
                <a class="nav-link active" href="{% url 'customer:user_register' %}">Register</a>
                <a class="nav-link active" href="{% url 'customer:user_login' %}">Login</a>
            {% endif %}
            <a class="nav-link active" href="{% url 'orders:cart' %}">CART {{ cart|length }}</a>
        </div>
    </div>
</nav>